{
    'name': 'TN-ITC',
    'version': '1',
    'summary': 'Phần Mềm Quản Lý',
    'sequence': 2,
    'description': '',
    'category': '',
    'author': '',
    'website': '',
    'license': 'LGPL-3',
    'depends': [
        'base',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/hieubt_customize.xml',
        'views/sanpham.xml',
        'views/nhomsanpham.xml',
        'views/donvitinh.xml',
        'views/khachhang.xml',
        'views/khuvuc.xml',
        'views/quanhuyen.xml',
        'views/noidungthuchi.xml',
        'views/noidungthuchi.xml',
        'views/students.xml',
        'views/timkiem.xml',
        'views/nhapxuat.xml',
        'views/nhapxuatchitiet.xml',
        'views/phanxuongsanxuat.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}